# Generated by Django 6.0.7 on 2026-07-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_pacas', models.PositiveIntegerField(default=0, editable=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='accounts.perfilusuario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.turno')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pacas', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.produccion')),
            ],
            options={
                'verbose_name': 'Detalle de Producción',
                'verbose_name_plural': 'Detalles de Producción',
            },
        ),
        migrations.CreateModel(
            name='Paca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=30, unique=True)),
                ('lote', models.PositiveIntegerField()),
                ('numero_paca', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacas', to='produccion.detalleproduccion')),
            ],
            options={
                'verbose_name': 'Paca',
                'verbose_name_plural': 'Pacas',
                'ordering': ['lote', 'numero_paca'],
                'constraints': [models.UniqueConstraint(fields=('detalle', 'lote', 'numero_paca'), name='lote_paca_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='detalleproduccion',
            constraint=models.UniqueConstraint(fields=('produccion', 'producto', 'color'), name='detalle_producto_color_unico'),
        ),
    ]
