# Generated by Django 6.0.7 on 2026-07-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
