# Generated by Django 6.0.6 on 2026-07-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.operador'),
        ),
    ]
