# Generated by Django 6.0.7 on 2026-07-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(choices=[('CARTON', 'Cartón'), ('DUPLEX', 'Duplex'), ('TINTE_LIQUIDO', 'Tinte Líquido'), ('TINTE_POLVO', 'Tinte en Polvo'), ('OTRO', 'Otro')], max_length=30)),
                ('fecha', models.DateField()),
                ('peso_cargado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_vacio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor')),
            ],
        ),
    ]
