# Generated by Django 6.0.6 on 2026-07-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unidades o bidones (Usado para Tintes)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='peso_cargado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usado para Cartón / Duplex', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='peso_neto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Peso Total Neto (Kg)'),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='peso_vacio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usado para Cartón / Duplex', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='tipo_material',
            field=models.CharField(choices=[('CARTON', 'Cartón'), ('DUPLEX', 'Duplex'), ('TINTE_MORADO', 'Tinte Morado (1 Tonelada = 1000 kg)'), ('TINTE_VERDE', 'Tinte Verde (1 Tonelada = 1000 kg)'), ('TINTE_AMARILLO', 'Tinte Amarillo (Sacos de 25 kg)'), ('TINTE_ROJO', 'Tinte Rojo (Sacos de 25 kg)'), ('OTRO', 'Otro')], max_length=30),
        ),
    ]
