# Generated by Django 6.0.6 on 2026-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_ingresomateriaprima_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='peso_cargado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='peso_neto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingresomateriaprima',
            name='peso_vacio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
