# Generated by Django 6.0.6 on 2026-07-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=25, unique=True)),
                ('fecha', models.DateField()),
                ('direccion_entrega', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('APLAZADO', 'Aplazado')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.transporte')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
