# Generated by Django 6.0.6 on 2026-07-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ventas.venta'),
        ),
    ]
