# Generated by Django 6.0.6 on 2026-07-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='venta',
        ),
        migrations.AddField(
            model_name='despacho',
            name='detalle_carga',
            field=models.TextField(blank=True, help_text='Descripción detallada de la mercadería a despachar', null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='total_pacas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
