# Generated by Django 6.0.6 on 2026-07-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0003_remove_despacho_venta_despacho_detalle_carga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despacho',
            options={},
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='detalle_carga',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='total_pacas',
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variedad', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='despachos.despacho')),
            ],
        ),
    ]
