# Generated by Django 6.0.6 on 2026-07-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('despachos', '0004_alter_despacho_options_remove_despacho_detalle_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledespacho',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto', verbose_name='Variedad'),
        ),
    ]
