# Generated by Django 6.0.7 on 2026-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('propietario', models.CharField(max_length=120, verbose_name='Propietario')),
                ('conductor', models.CharField(max_length=120, verbose_name='Conductor')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad (Kg)')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['placa'],
            },
        ),
    ]
