# Generated by Django 6.0.6 on 2026-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='identificacion',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Identificación / Cédula'),
        ),
    ]
