# Generated by Django 6.0.6 on 2026-07-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rol_perfilusuario_cargo_perfilusuario_rol'),
        ('catalogos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=25, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad_pacas', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='catalogos.color', verbose_name='Color')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='catalogos.producto', verbose_name='Modelo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
