# Generated by Django 6.0.6 on 2026-07-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_cantidad_pacas_remove_venta_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='transporte',
        ),
    ]
